//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsClient.NewsClientRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewsArticle", Namespace="http://schemas.datacontract.org/2004/07/NewsService")]
    [System.SerializableAttribute()]
    public partial class NewsArticle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NewsClient.NewsClientRef.Person PostedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopicField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NewsClient.NewsClientRef.Person PostedBy {
            get {
                return this.PostedByField;
            }
            set {
                if ((object.ReferenceEquals(this.PostedByField, value) != true)) {
                    this.PostedByField = value;
                    this.RaisePropertyChanged("PostedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Topic {
            get {
                return this.TopicField;
            }
            set {
                if ((object.ReferenceEquals(this.TopicField, value) != true)) {
                    this.TopicField = value;
                    this.RaisePropertyChanged("Topic");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/NewsService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NewsClient.NewsClientRef.Journalist))]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Journalist", Namespace="http://schemas.datacontract.org/2004/07/NewsService")]
    [System.SerializableAttribute()]
    public partial class Journalist : NewsClient.NewsClientRef.Person {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AffiliationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Affiliation {
            get {
                return this.AffiliationField;
            }
            set {
                if ((object.ReferenceEquals(this.AffiliationField, value) != true)) {
                    this.AffiliationField = value;
                    this.RaisePropertyChanged("Affiliation");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewsClientRef.INewsServiceWCF")]
    public interface INewsServiceWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsServiceWCF/GetArticles", ReplyAction="http://tempuri.org/INewsServiceWCF/GetArticlesResponse")]
        NewsClient.NewsClientRef.NewsArticle[] GetArticles(string topic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsServiceWCF/GetArticles", ReplyAction="http://tempuri.org/INewsServiceWCF/GetArticlesResponse")]
        System.Threading.Tasks.Task<NewsClient.NewsClientRef.NewsArticle[]> GetArticlesAsync(string topic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsServiceWCF/PostArticle", ReplyAction="http://tempuri.org/INewsServiceWCF/PostArticleResponse")]
        NewsClient.NewsClientRef.NewsArticle PostArticle(NewsClient.NewsClientRef.NewsArticle article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INewsServiceWCF/PostArticle", ReplyAction="http://tempuri.org/INewsServiceWCF/PostArticleResponse")]
        System.Threading.Tasks.Task<NewsClient.NewsClientRef.NewsArticle> PostArticleAsync(NewsClient.NewsClientRef.NewsArticle article);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INewsServiceWCFChannel : NewsClient.NewsClientRef.INewsServiceWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewsServiceWCFClient : System.ServiceModel.ClientBase<NewsClient.NewsClientRef.INewsServiceWCF>, NewsClient.NewsClientRef.INewsServiceWCF {
        
        public NewsServiceWCFClient() {
        }
        
        public NewsServiceWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewsServiceWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsServiceWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewsServiceWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NewsClient.NewsClientRef.NewsArticle[] GetArticles(string topic) {
            return base.Channel.GetArticles(topic);
        }
        
        public System.Threading.Tasks.Task<NewsClient.NewsClientRef.NewsArticle[]> GetArticlesAsync(string topic) {
            return base.Channel.GetArticlesAsync(topic);
        }
        
        public NewsClient.NewsClientRef.NewsArticle PostArticle(NewsClient.NewsClientRef.NewsArticle article) {
            return base.Channel.PostArticle(article);
        }
        
        public System.Threading.Tasks.Task<NewsClient.NewsClientRef.NewsArticle> PostArticleAsync(NewsClient.NewsClientRef.NewsArticle article) {
            return base.Channel.PostArticleAsync(article);
        }
    }
}
